# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "talleres-mecanicos", "name": "Talleres mecánicos", "icon": "wrench",
 "color": {"s": "#475569", "dark": "#334155", "light": "#cbd5e1", "soft": "#f1f5f9", "rgb": "71,85,105"},
 "credits": "Gustavo Fring y Renee Razumov en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-taller-mecanico-revision", "alt": "Mecánico revisando el motor de un coche en un taller"},
 "img2": {"file": "verantia-taller-taller-limpio", "alt": "Taller mecánico ordenado y limpio, con herramientas y elevador, sin personas"},
 "hero": {
  "h1": "Inteligencia artificial para <em>talleres mecánicos</em>",
  "lead": "Clientes atendidos y avisados sin soltar la llave inglesa. Somos especialistas en "
          "<strong>IA para talleres mecánicos en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, avisos automáticos a tus clientes y reseñas en Google, con presupuestos ajustados a tu taller.",
  "chips": ["Atención por WhatsApp y teléfono", "Avisos de revisión e ITV", "Más reseñas en Google"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en un taller",
  "sub": "Manos en el motor, coches en el elevador y un teléfono que no para. Seguro que te suena.",
  "items": [
   ("chat", "«¿Cómo va mi coche?»", "Te escriben por WhatsApp para pedir cita, preguntar precios o saber cómo va la reparación, y contestas cuando puedes."),
   ("phone", "El teléfono con las manos llenas de grasa", "Debajo de un coche no puedes coger el teléfono, y esa llamada suele ser un cliente nuevo que acaba llamando a otro taller."),
   ("bell", "Avisos que se hacen a mano", "Avisar de que el coche está listo, recordar la revisión o la ITV, enviar el presupuesto. Todo depende de que alguien se acuerde."),
   ("star", "Reseñas que nunca llegan", "Tus clientes se van contentos, pero casi ninguno deja su opinión en Google si nadie se lo recuerda."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual cada semana, y eso es exactamente lo que se puede automatizar sin perder la confianza que tus clientes tienen en tu taller."},
 "services": {
  "eyebrow": "Soluciones para tu taller", "h2": "Los 4 servicios más populares en talleres mecánicos",
  "sub": "Dos asistentes que atienden por ti y dos automatizaciones que mantienen a tus clientes informados y hacen crecer tu ficha de Google. Puedes empezar por uno solo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente que conoce tus servicios, tus horarios y tu forma de trabajar, y que responde a tus clientes al momento, a cualquier hora, y les da cita.",
    "bullets": ["Informa de servicios, horarios y precios orientativos que tú defines.",
                "Da cita para revisiones, cambios de aceite, neumáticos o pre-ITV.",
                "Recoge los datos del coche y la avería antes de que llegue al taller.",
                "Te pasa las consultas de presupuesto para que las revises tú."],
    "result": "ningún cliente se queda sin respuesta, aunque estés debajo de un coche o con el taller cerrado."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas y da cita. Lo desarrollamos a medida para tu taller.",
    "bullets": ["Contesta cuando estás con las manos en el motor o con el taller cerrado.",
                "Informa de horarios y servicios, y da cita en tu agenda.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Habla con el tono de tu taller y siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada se queda sin atender mientras trabajas."},
   {"icon": "bell", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Avisos automáticos a tus clientes",
    "desc": "Automatizamos los avisos que hoy haces a mano para que tus clientes estén informados y vuelvan cuando les toca.",
    "bullets": ["Aviso por WhatsApp cuando el coche está listo para recoger.",
                "Envío del presupuesto para que el cliente lo acepte por escrito.",
                "Recordatorio de la próxima revisión, el cambio de aceite o la ITV.",
                "Recordatorio de cita el día anterior, con la dirección del taller."],
    "result": "menos llamadas preguntando y clientes que vuelven a tu taller cuando toca."},
   {"icon": "star", "base": "resenas-automaticas-google", "link": "Ver reseñas automáticas en Google",
    "title": "Más reseñas en Google después de cada reparación",
    "desc": "Al recoger el coche, tu cliente recibe un mensaje amable de agradecimiento con el enlace directo para valorar tu taller en Google.",
    "bullets": ["Se envía cuando la experiencia está más reciente.",
                "Llega a todos los clientes por igual, como exigen las normas de Google.",
                "Sin descuentos a cambio de reseñas: está prohibido y pone en riesgo tu ficha.",
                "Te avisa de cada reseña nueva para que puedas responderla."],
    "result": "una ficha de Google más completa y activa, que es lo primero que mira quien busca un taller de confianza."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("clasificador-de-leads", "Clasificador de leads"), ("auditoria-de-procesos", "Auditoría de procesos gratuita"), ("aplicaciones-personalizadas", "Aplicaciones personalizadas")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "Coches más viejos, más visitas al taller, y clientes que comparan",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("Lo que miran", "89", 0, "%", "de los españoles consulta reseñas online antes de comprar. Antes de elegir taller, también.", "Skeepers · 2025"),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("Ya lo hacen", "55", 0, "%", "de las empresas españolas ya usa WhatsApp para comunicarse con sus clientes.", "HubSpot · 2026"),
   ("La oportunidad", "16.9", 1, " años", "de antigüedad media tienen los turismos en Castilla y León, frente a 14,6 en el conjunto de España. Más mantenimiento, más visitas al taller.", "ANFAC · 2025"),
  ],
  "sources": sources(SKEEPERS, ZENDESK, HUBSPOT, ANFAC)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera llamada a la reseña, sin salir del foso",
  "sub": "El recorrido de un cliente en tu taller, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de los coches. Lo demás funciona solo.",
  "items": [
   ("phone", "<b>Pregunta.</b> Llama por teléfono o escribe por WhatsApp para pedir cita o contar la avería, y recibe respuesta al momento."),
   ("calok", "<b>Cita.</b> El asistente le da cita en tu agenda y te deja apuntados los datos del coche y lo que le pasa."),
   ("wrench", "<b>Reparación.</b> Recibe el presupuesto por WhatsApp para aceptarlo, y el aviso cuando el coche está listo."),
   ("star", "<b>Reseña.</b> Al recoger el coche recibe un mensaje de agradecimiento con el enlace para valorar tu taller en Google."),
   ("bell", "<b>Vuelve.</b> Cuando se acerca la próxima revisión o la ITV, recibe un recordatorio para volver a tu taller."),
  ]},
 "steps": STEPS("taller", "las citas, los mensajes, las llamadas y los avisos",
                "Cargamos tus servicios, horarios, precios orientativos y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono y tu programa de gestión del taller."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para talleres mecánicos en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("el programa del taller", "tu programa de gestión del taller"),
   ("¿El asistente da presupuestos?",
    "<p>Solo los precios orientativos que tú le indiques, como un cambio de aceite o un juego de neumáticos. Las averías y las reparaciones las presupuestas tú.</p>"
    "<p>El asistente recoge los datos del coche y lo que le pasa, y te los pasa para que prepares el presupuesto sin tener que volver a preguntar.</p>"),
   faq_phone("cuando estás con las manos en el motor", "horarios y servicios, da cita en tu agenda"),
   ("¿Cómo sabe cuándo le toca la revisión o la ITV a cada cliente?",
    "<p>A partir de los datos que ya guardas: fecha de la última revisión, kilómetros o fecha de matriculación. Tú decides con cuánta antelación se envía el aviso.</p>"
    "<p>Si esos datos están repartidos en papel o en varias herramientas, lo vemos en la auditoría y te proponemos cómo ordenarlos.</p>"),
   faq_datos("clientes"),
   ("¿Pedir reseñas de forma automática está permitido por Google?",
    "<p>Sí. Pedir reseñas está permitido. Lo que Google prohíbe es ofrecer algo a cambio y pedírselas solo a los clientes contentos dejando fuera al resto.</p>"
    "<p>Por eso nuestro sistema pide la reseña a todos por igual y sin incentivos: tu ficha crece sin ponerla en riesgo.</p>"),
   faq_precio("un taller"),
   faq_zona("talleres"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a los coches, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu taller: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para talleres mecánicos",
 "schema_desc": "IA para talleres mecánicos en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, avisos automáticos a clientes y reseñas en Google.",
 "yoast": yoast("IA para talleres mecánicos en Valladolid", "citas por WhatsApp y teléfono, avisos de coche listo, revisión e ITV y reseñas en Google. Auditoría gratuita."),
}
