# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "academias", "name": "Academias", "icon": "grad",
 "color": {"s": "#4f46e5", "dark": "#3730a3", "light": "#c7d2fe", "soft": "#eef2ff", "rgb": "79,70,229"},
 "credits": "Gustavo Fring y Polina Tankilevitch en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-academia-clase-profesora", "alt": "Profesora dando clase de apoyo a dos alumnas en un aula luminosa"},
 "img2": {"file": "verantia-academia-cuaderno-estudio", "alt": "Manos tomando apuntes en un cuaderno durante una clase"},
 "hero": {
  "h1": "Inteligencia artificial para <em>academias</em>",
  "lead": "Más matrículas y menos horas al teléfono, sin descuidar las clases. Somos especialistas en "
          "<strong>IA para academias en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, gestión de solicitudes de información y automatización de matrículas y avisos.",
  "chips": ["Respuesta inmediata a cada familia", "Ninguna solicitud olvidada", "Matrículas y avisos automáticos"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en una academia",
  "sub": "Clases toda la tarde, familias que preguntan a todas horas y papeleo que se acumula. Seguro que te suena.",
  "items": [
   ("chat", "Preguntas mientras das clase", "Horarios, precios, grupos, niveles… las familias escriben por WhatsApp justo cuando estás en el aula."),
   ("phone", "Llamadas que no puedes coger", "En plena clase no puedes atender el teléfono, y quien llama para informarse acaba probando en otra academia."),
   ("funnel", "Solicitudes que se enfrían", "Entran pidiendo información por la web o las redes, pero entre clase y clase se quedan sin seguimiento."),
   ("doc", "Matrículas y cobros a mano", "Fichas, altas, avisos de pago y comunicados a las familias, uno por uno, cada mes."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual cada curso, y eso es exactamente lo que se puede automatizar sin perder el trato cercano con alumnos y familias."},
 "services": {
  "eyebrow": "Soluciones para tu academia", "h2": "Los 4 servicios más populares en academias",
  "sub": "Dos asistentes que atienden por ti, uno que ordena las solicitudes y una automatización que se ocupa del papeleo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente entrenado con tus cursos, horarios y precios que responde a alumnos y familias al momento, a cualquier hora.",
    "bullets": ["Explica cursos, niveles, horarios, precios y plazas disponibles.",
                "Agenda pruebas de nivel y clases de prueba.",
                "Recoge los datos de quien pide información para que no se pierda.",
                "Deriva a una persona las dudas sobre casos concretos de cada alumno."],
    "result": "ninguna familia se queda sin respuesta, aunque estés dando clase o la academia esté cerrada."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas y agenda pruebas de nivel. Lo desarrollamos a medida para tu academia.",
    "bullets": ["Contesta cuando estás en clase, en época de matrículas o con la academia cerrada.",
                "Informa de cursos, horarios y precios.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada de un futuro alumno se queda sin atender."},
   {"icon": "funnel", "base": "clasificador-de-leads", "link": "Ver clasificador de leads",
    "title": "Clasificador de solicitudes de información",
    "desc": "Ordena automáticamente a quienes piden información según su interés real y urgencia, para que llames primero a quien está a punto de matricularse.",
    "bullets": ["Reúne en un solo sitio las solicitudes de la web, WhatsApp y redes.",
                "Las prioriza según el curso, la fecha de inicio y lo que ha preguntado cada persona.",
                "Te avisa de las más urgentes al momento.",
                "Registra el seguimiento para que ninguna se quede olvidada."],
    "result": "más solicitudes convertidas en matrículas, dedicando el tiempo a quien de verdad va a empezar."},
   {"icon": "doc", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Matrículas, cobros y avisos automáticos",
    "desc": "Automatizamos el papeleo que hoy haces a mano cada mes, conectando las herramientas que ya usas.",
    "bullets": ["Formulario de matrícula que rellena la ficha del alumno sin copiar datos.",
                "Recordatorios de pago y de documentación pendiente.",
                "Comunicados a las familias por grupo: cambios de horario, festivos, exámenes.",
                "Avisos de renovación antes de cada trimestre o curso."],
    "result": "menos horas de oficina y menos errores al pasar datos de un sitio a otro."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("resenas-automaticas-google", "Reseñas automáticas en Google"), ("auditoria-de-procesos", "Auditoría de procesos gratuita"), ("aplicaciones-personalizadas", "Aplicaciones personalizadas")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "La demanda existe, y gana quien responde primero",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "23", 0, "%", "de las empresas nunca respondió a una solicitud de información recibida por su web. Cada una es un alumno que se va a otra academia.", "HBR · EE. UU."),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("La demanda", "25", 0, "%", "de los estudiantes de 6 a 18 años en España recibe clases particulares o de refuerzo.", "Fundación «la Caixa» · 2026"),
   ("La oportunidad", "48", 0, "%", "más gastan hoy las familias de Castilla y León en refuerzo educativo que antes de la pandemia, en términos reales.", "EsadeEcPol · 2026"),
  ],
  "sources": sources(HBR, ZENDESK, LACAIXA, ESADE)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera pregunta a la matrícula, sin salir del aula",
  "sub": "El recorrido de un nuevo alumno en tu academia, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de las clases. Lo demás funciona solo.",
  "items": [
   ("chat", "<b>Pregunta.</b> Una familia escribe por WhatsApp o llama para preguntar por horarios y precios, y recibe respuesta al momento."),
   ("funnel", "<b>Solicitud.</b> Sus datos quedan registrados y priorizados, y te avisa si está lista para empezar pronto."),
   ("calok", "<b>Prueba de nivel.</b> El asistente le ofrece los huecos libres y deja la cita apuntada."),
   ("doc", "<b>Matrícula.</b> Rellena el formulario una vez y su ficha, su grupo y sus pagos quedan listos sin copiar datos."),
   ("bell", "<b>Seguimiento.</b> Recibe los avisos de pago, comunicados y renovaciones de forma automática durante todo el curso."),
  ]},
 "steps": STEPS("academia", "las consultas, las solicitudes de información, las matrículas y los cobros",
                "Cargamos tus cursos, horarios, precios y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono y tus herramientas de gestión."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para academias en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("el programa de gestión", "tu programa"),
   ("¿El asistente puede orientar sobre qué curso elegir?",
    "<p>Sí, a partir de la información que tú le das: niveles, edades, objetivos de cada curso y requisitos. Puede orientar y proponer una prueba de nivel.</p>"
    "<p>Lo que no hace es evaluar a un alumno: esa decisión la toma siempre tu equipo docente.</p>"),
   faq_phone("cuando estás dando clase", "cursos, horarios y precios, agenda pruebas de nivel"),
   faq_datos("alumnos y sus familias"),
   ("¿Qué pasa con los datos de alumnos menores de edad?",
    "<p>Los tratamos con especial cuidado: el asistente se dirige a padres, madres o tutores, y no pide por chat más datos de los imprescindibles para informar o matricular.</p>"
    "<p>Configuramos cada flujo contigo para que cumpla el RGPD y la normativa de protección de menores.</p>"),
   ("¿Sirve para academias de idiomas, oposiciones o refuerzo escolar?",
    "<p>Sí. Cambian los cursos y las preguntas, pero el trabajo es el mismo: responder rápido, no perder solicitudes y quitar papeleo. Adaptamos cada solución a tu tipo de academia.</p>"),
   faq_precio("una academia"),
   faq_zona("academias"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a las clases, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu academia: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para academias",
 "schema_desc": "IA para academias en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, gestión de solicitudes de información y automatización de matrículas.",
 "yoast": yoast("IA para academias en Valladolid", "asistentes de WhatsApp y teléfono, gestión de solicitudes y matrículas automáticas. Auditoría gratuita."),
}
