# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "inmobiliarias", "name": "Inmobiliarias", "icon": "key",
 "color": {"s": "#0e7490", "dark": "#155e75", "light": "#a5f3fc", "soft": "#ecfeff", "rgb": "14,116,144"},
 "credits": "RDNE Stock Project y Artbovich en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-inmobiliaria-visita-vivienda", "alt": "Agente inmobiliaria enseñando una vivienda luminosa a un cliente"},
 "img2": {"file": "verantia-inmobiliaria-salon-vacio", "alt": "Salón vacío y luminoso de una vivienda en venta"},
 "hero": {
  "h1": "Inteligencia artificial para <em>inmobiliarias</em>",
  "lead": "Cada contacto atendido al momento, aunque estés enseñando un piso. Somos especialistas en "
          "<strong>IA para inmobiliarias en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, clasificación de contactos y automatización del seguimiento y las visitas.",
  "chips": ["Respuesta inmediata a cada contacto", "Compradores reales, primero", "Visitas y seguimiento automáticos"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en una inmobiliaria",
  "sub": "Visitas toda la mañana, portales que no paran de enviar contactos y un móvil que suena en mitad de cada enseñanza.",
  "items": [
   ("chat", "Mensajes sobre cada anuncio", "¿Sigue disponible? ¿Admite mascotas? ¿Tiene garaje? Las mismas preguntas por WhatsApp y portales, a todas horas."),
   ("phone", "Llamadas durante las visitas", "No puedes coger el teléfono mientras enseñas un piso, y el interesado que llama prueba con la siguiente agencia."),
   ("funnel", "Curiosos y compradores, mezclados", "Dedicas el mismo tiempo a quien solo mira que a quien tiene la hipoteca aprobada y quiere visitar esta semana."),
   ("calok", "Seguimiento y visitas a mano", "Coordinar visitas, recordarlas y volver a llamar a cada contacto se hace a golpe de agenda y memoria."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual con cada inmueble, y eso es exactamente lo que se puede automatizar sin perder el trato personal que cierra una operación."},
 "services": {
  "eyebrow": "Soluciones para tu inmobiliaria", "h2": "Los 4 servicios más populares en inmobiliarias",
  "sub": "Dos asistentes que atienden por ti, uno que separa a los compradores de los curiosos y una automatización para visitas y seguimiento.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente que conoce tu cartera de inmuebles y responde a cada interesado al momento, a cualquier hora, con los datos del anuncio que pregunta.",
    "bullets": ["Responde precio, metros, gastos, disponibilidad y características de cada inmueble.",
                "Propone inmuebles parecidos si el que pregunta ya no está disponible.",
                "Ofrece huecos para visitar y los reserva en tu agenda.",
                "Recoge qué busca cada contacto para que tengas el perfil completo."],
    "result": "ningún interesado se queda sin respuesta, aunque estés en una visita o sea domingo."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas sobre los inmuebles y agenda visitas. Lo desarrollamos a medida para tu inmobiliaria.",
    "bullets": ["Contesta cuando estás enseñando un piso, en una firma o con la oficina cerrada.",
                "Informa de los inmuebles por los que llaman y ofrece visitas.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada de un posible comprador se queda sin atender."},
   {"icon": "funnel", "base": "clasificador-de-leads", "link": "Ver clasificador de leads",
    "title": "Clasificador de compradores y propietarios",
    "desc": "Ordena automáticamente cada contacto según su interés real y urgencia, para que dediques tu tiempo a quien está listo para comprar, alquilar o vender.",
    "bullets": ["Reúne en un solo sitio los contactos de portales, web, WhatsApp y teléfono.",
                "Los prioriza según presupuesto, zona, plazos y si necesitan financiación.",
                "Detecta a los propietarios que quieren vender o alquilar su vivienda.",
                "Te avisa de los más calientes al momento."],
    "result": "más visitas útiles y más operaciones, con menos tiempo perdido."},
   {"icon": "calok", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Visitas, seguimiento y documentación automáticos",
    "desc": "Automatizamos las tareas repetitivas que hay alrededor de cada operación, conectando las herramientas que ya usas.",
    "bullets": ["Confirmación y recordatorio de cada visita por WhatsApp.",
                "Mensajes de seguimiento después de la visita, en el momento oportuno.",
                "Aviso a los contactos interesados cuando entra un inmueble que encaja con lo que buscan.",
                "Petición y control de la documentación pendiente de cada operación."],
    "result": "menos visitas fallidas, ningún contacto olvidado y menos papeleo."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("ia-generativa-contenido-visual", "Fotos y textos de anuncios con IA"), ("resenas-automaticas-google", "Reseñas automáticas en Google"), ("auditoria-de-procesos", "Auditoría de procesos gratuita")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "El mercado se mueve, y gana quien responde primero",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "23", 0, "%", "de las empresas nunca respondió a una solicitud de información recibida por su web. Cada una es un cliente para otra agencia.", "HBR · EE. UU."),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("El mercado", "714237", 0, "", "compraventas de viviendas en España en 2025, un 11,5 % más que el año anterior.", "INE · 2025"),
   ("La oportunidad", "18.9", 1, "%", "crecieron las compraventas de viviendas en Castilla y León en 2025, más que en ninguna otra comunidad.", "INE · 2025"),
  ],
  "sources": sources(HBR, ZENDESK, INE_VIV)},
 "day": {
  "eyebrow": "Así funciona", "h2": "Del primer mensaje a la visita, sin perder ningún contacto",
  "sub": "El recorrido de un interesado en tu inmobiliaria, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de enseñar y cerrar. Lo demás funciona solo.",
  "items": [
   ("chat", "<b>Pregunta.</b> Ve un anuncio y escribe por WhatsApp o llama. Recibe al momento la información del inmueble."),
   ("funnel", "<b>Clasificación.</b> Su perfil queda registrado y priorizado, y te avisa si está listo para comprar pronto."),
   ("calok", "<b>Visita.</b> El asistente le ofrece huecos y deja la visita apuntada en tu agenda, con recordatorio incluido."),
   ("key", "<b>Enseñanza.</b> Tú te dedicas por completo a la visita, sin interrupciones del teléfono."),
   ("bell", "<b>Seguimiento.</b> Después recibe el mensaje de seguimiento en el momento justo, y un aviso si entra otro inmueble que encaje."),
  ]},
 "steps": STEPS("inmobiliaria", "los contactos, las llamadas, las visitas y el seguimiento",
                "Cargamos tu cartera de inmuebles, tus condiciones y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono, tu web y los portales que uses."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para inmobiliarias en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("mi CRM inmobiliario", "tu CRM"),
   ("¿Cómo sabe el asistente qué inmuebles tengo disponibles?",
    "<p>Lo conectamos a tu cartera: tu CRM, tu web o el listado que uses. Cuando un inmueble se reserva o se vende, deja de ofrecerlo.</p>"
    "<p>Si la conexión automática no es posible, te proponemos una forma sencilla de mantenerlo actualizado sin trabajo extra.</p>"),
   faq_phone("cuando estás enseñando un piso", "los inmuebles por los que preguntan, ofrece visitas"),
   faq_datos("clientes"),
   ("¿Sirve para alquiler y para captar propietarios?",
    "<p>Sí. El asistente y el clasificador distinguen entre quien busca comprar, alquilar o vender, y te pasan a cada uno por su camino. Captar propietarios es uno de los usos que más valoran las agencias.</p>"),
   ("¿Puede el asistente negociar el precio?",
    "<p>No, y no debe. Informa de las condiciones publicadas y recoge la propuesta del interesado, pero cualquier negociación la llevas tú. Es una decisión que siempre tiene que tomar una persona.</p>"),
   faq_precio("una inmobiliaria"),
   faq_zona("inmobiliarias"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a cerrar operaciones, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu inmobiliaria: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para inmobiliarias",
 "schema_desc": "IA para inmobiliarias en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, clasificación de contactos y automatización de visitas y seguimiento.",
 "yoast": yoast("IA para inmobiliarias en Valladolid", "asistentes de WhatsApp y teléfono, clasificación de contactos y visitas automáticas. Auditoría gratuita."),
}
