# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "tiendas-online", "name": "Tiendas online", "icon": "cart",
 "color": {"s": "#c2410c", "dark": "#9a3412", "light": "#fed7aa", "soft": "#fff7ed", "rgb": "194,65,12"},
 "credits": "Kampus Production en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-ecommerce-preparando-pedidos", "alt": "Emprendedora preparando pedidos de su tienda online junto a cajas de envío"},
 "img2": {"file": "verantia-ecommerce-etiquetando-paquete", "alt": "Manos etiquetando una caja de cartón para un envío"},
 "hero": {
  "h1": "Inteligencia artificial para <em>tiendas online</em>",
  "lead": "Más ventas y menos horas contestando lo mismo. Somos especialistas en "
          "<strong>IA para tiendas online en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, automatización de pedidos y contenido de producto creado con IA.",
  "chips": ["Atención al cliente a cualquier hora", "Pedidos sin tareas manuales", "Fichas de producto con IA"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en una tienda online",
  "sub": "Preparar pedidos, contestar dudas y subir productos, todo a la vez. Seguro que te suena.",
  "items": [
   ("chat", "«¿Dónde está mi pedido?»", "Las mismas preguntas sobre envíos, tallas y devoluciones llegan cada día por WhatsApp, correo y redes."),
   ("phone", "Llamadas mientras empaquetas", "Con las manos en las cajas no puedes coger el teléfono, y el cliente con una duda antes de comprar se va."),
   ("box", "Pedidos, stock y facturas a mano", "Pasar datos de la tienda a la hoja de stock, a la agencia de transporte y a la facturación, pedido a pedido."),
   ("camera", "Fichas de producto que nunca acaban", "Cada producto nuevo necesita fotos, descripciones y textos para redes, y siempre van con retraso."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual con cada pedido y cada producto, y eso es exactamente lo que se puede automatizar sin perder la cercanía de una marca pequeña."},
 "services": {
  "eyebrow": "Soluciones para tu tienda", "h2": "Los 4 servicios más populares en tiendas online",
  "sub": "Dos asistentes que atienden por ti, una automatización para los pedidos y la IA generativa para tu catálogo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente entrenado con tu catálogo y tus políticas que resuelve las dudas de tus clientes al momento, antes y después de comprar.",
    "bullets": ["Responde sobre tallas, materiales, disponibilidad y plazos de envío.",
                "Consulta el estado de un pedido y se lo explica al cliente.",
                "Explica cómo hacer cambios y devoluciones según tu política.",
                "Deriva a una persona las incidencias que necesitan revisión."],
    "result": "dudas resueltas al momento, menos carritos abandonados por falta de respuesta y menos correos repetidos."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas sobre productos y pedidos. Lo desarrollamos a medida para tu tienda.",
    "bullets": ["Contesta cuando estás preparando envíos o fuera de horario.",
                "Informa sobre productos, envíos y el estado de los pedidos.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada de un cliente se queda sin atender."},
   {"icon": "box", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Pedidos, stock y facturas automáticos",
    "desc": "Conectamos tu tienda con las herramientas que ya usas para que los datos de cada pedido viajen solos.",
    "bullets": ["Cada pedido actualiza el stock y genera la etiqueta de envío sin copiar datos.",
                "Facturas creadas y enviadas automáticamente.",
                "Aviso al cliente en cada paso: preparado, enviado, entregado.",
                "Alertas de stock bajo antes de que un producto se agote."],
    "result": "menos horas de gestión y menos errores al pasar datos de un sitio a otro."},
   {"icon": "sparkle", "base": "ia-generativa-contenido-visual", "link": "Ver IA generativa y contenido visual",
    "title": "Fichas de producto y contenido con IA",
    "desc": "Creamos con inteligencia artificial las descripciones, las imágenes y los textos para redes de tu catálogo, con el tono de tu marca.",
    "bullets": ["Descripciones de producto claras y pensadas para buscadores.",
                "Fotos de producto mejoradas y fondos consistentes.",
                "Textos para redes y campañas de temporada.",
                "Siempre revisado por ti antes de publicarse."],
    "result": "un catálogo completo y cuidado, sin que se acumulen los productos pendientes de subir."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("resenas-automaticas-google", "Reseñas automáticas en Google"), ("clasificador-de-leads", "Clasificador de leads"), ("auditoria-de-procesos", "Auditoría de procesos gratuita")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "El comercio online crece, y el cliente no espera",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "70.2", 1, "%", "de los carritos de compra online se abandonan antes de pagar, según la media de 50 estudios.", "Baymard Institute · 2025"),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("El mercado", "114800", 0, "M€", "facturó el comercio electrónico en España en 2025, un 20,6 % más que el año anterior.", "CNMC · 2025"),
   ("Ya lo hacen", "55", 0, "%", "de las empresas españolas ya usa WhatsApp para comunicarse con sus clientes.", "HubSpot · 2026"),
  ],
  "sources": sources(BAYMARD, ZENDESK, CNMC, HUBSPOT)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera duda a la entrega, sin tareas repetidas",
  "sub": "El recorrido de un cliente en tu tienda, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de tu marca y tus productos. Lo demás funciona solo.",
  "items": [
   ("sparkle", "<b>Descubre.</b> Encuentra un producto con una ficha completa, fotos cuidadas y una descripción clara."),
   ("chat", "<b>Pregunta.</b> Tiene una duda sobre la talla o el envío y recibe respuesta al momento, por escrito o por teléfono."),
   ("cart", "<b>Compra.</b> El pedido actualiza el stock, genera la etiqueta y la factura sin que toques nada."),
   ("box", "<b>Envío.</b> Recibe un aviso en cada paso: preparado, enviado y entregado."),
   ("chat", "<b>Posventa.</b> Si quiere cambiar algo, el asistente le explica cómo hacerlo según tu política."),
  ]},
 "steps": STEPS("tienda", "la atención al cliente, los pedidos, el stock y el catálogo",
                "Cargamos tu catálogo, tus políticas de envío y devolución y tu forma de hablar. Conectamos tu tienda, tu WhatsApp y tus herramientas."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para tiendas online en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   ("¿Funciona con mi plataforma de tienda online?",
    "<p>Depende de la plataforma. Las más habituales, como WooCommerce, Shopify o PrestaShop, permiten conectarse con otras herramientas, y en ese caso lo integramos directamente.</p>"
    f"<p>Lo comprobamos en la {AUD}, antes de que decidas nada.</p>"),
   ("¿El asistente puede consultar el estado de un pedido?",
    "<p>Sí, si lo conectamos con tu tienda y tu agencia de transporte. El cliente da su número de pedido y el asistente le explica en qué punto está.</p>"
    "<p>Si hay una incidencia, como un paquete perdido o un producto dañado, se la pasa a una persona.</p>"),
   faq_phone("cuando estás preparando envíos", "productos, envíos y el estado de los pedidos"),
   faq_datos("clientes"),
   ("¿Los textos creados con IA son buenos para buscadores?",
    "<p>Sí, si se hacen bien: descripciones originales, útiles para el cliente y con las palabras que de verdad busca. No publicamos texto genérico ni duplicado, y tú revisas cada ficha antes de que salga.</p>"),
   ("¿Podéis ayudarme a recuperar carritos abandonados?",
    "<p>Sí. Podemos automatizar un recordatorio al cliente que dejó el carrito a medias, siempre respetando su consentimiento para recibir comunicaciones, como exige la normativa.</p>"),
   faq_precio("una tienda online"),
   faq_zona("tiendas online"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a tu marca, no a tareas repetidas",
         "p": "Empezamos con una auditoría gratuita de tu tienda: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para tiendas online",
 "schema_desc": "IA para tiendas online en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, automatización de pedidos y fichas de producto con IA.",
 "yoast": yoast("IA para tiendas online en Valladolid", "asistentes de WhatsApp y teléfono, pedidos automáticos y fichas de producto con IA. Auditoría gratuita."),
}
