# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "gimnasios", "name": "Gimnasios", "icon": "dumbbell",
 "color": {"s": "#15803d", "dark": "#166534", "light": "#bbf7d0", "soft": "#f0fdf4", "rgb": "21,128,61"},
 "credits": "Julia Larson y jdgromov en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-gimnasio-entrenador-cliente", "alt": "Entrenador personal acompañando a un cliente durante un ejercicio en el gimnasio"},
 "img2": {"file": "verantia-gimnasio-sala-maquinas", "alt": "Sala de máquinas de un gimnasio moderno, sin personas"},
 "hero": {
  "h1": "Inteligencia artificial para <em>gimnasios</em>",
  "lead": "Más altas, menos bajas y una recepción que no se colapsa. Somos especialistas en "
          "<strong>IA para gimnasios en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, seguimiento de interesados y avisos automáticos a tus socios, con presupuestos ajustados a tu centro.",
  "chips": ["Atención por WhatsApp y teléfono", "Más pruebas que acaban en alta", "Socios que no se pierden"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en un gimnasio",
  "sub": "Clases llenas, entrenamientos en marcha y una recepción que no llega a todo. Seguro que te suena.",
  "items": [
   ("chat", "Las mismas preguntas una y otra vez", "Horarios, tarifas, matrícula, qué clases hay hoy. Llegan por WhatsApp a todas horas y alguien tiene que dejar lo que está haciendo para contestar."),
   ("phone", "El teléfono sin nadie que lo coja", "Con el equipo dando clase o entrenando a un cliente, la llamada de alguien que quiere apuntarse se queda sin respuesta."),
   ("funnel", "Interesados que se enfrían", "Alguien pide información o viene a probar y nadie le vuelve a escribir. Al final se apunta en otro sitio."),
   ("users", "Socios que se van sin avisar", "Un socio deja de venir, nadie lo nota a tiempo y un mes después llega la baja. Además, cuotas y renovaciones se revisan a mano."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual cada semana, y eso es exactamente lo que se puede automatizar sin perder el trato cercano de tu gimnasio."},
 "services": {
  "eyebrow": "Soluciones para tu gimnasio", "h2": "Los 4 servicios más populares en gimnasios",
  "sub": "Dos asistentes que atienden por ti y dos automatizaciones que convierten interesados en socios y cuidan a los que ya tienes. Puedes empezar por uno solo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente que conoce tus horarios, tus tarifas y tus clases, y que responde a socios e interesados al momento, a cualquier hora.",
    "bullets": ["Informa de horarios, tarifas, matrícula y actividades.",
                "Reserva plaza en clases dirigidas o en una sesión de prueba.",
                "Resuelve dudas frecuentes de socios: cambios de cuota, congelaciones, horarios de festivos.",
                "Habla con el tono de tu gimnasio, cercano y motivador."],
    "result": "ninguna consulta se queda sin respuesta, aunque tu equipo esté en sala o el centro esté cerrado."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tu equipo no puede coger: resuelve dudas y reserva sesiones de prueba. Lo desarrollamos a medida para tu gimnasio.",
    "bullets": ["Contesta cuando recepción está ocupada, en horas punta o fuera de horario.",
                "Informa de horarios, tarifas y actividades, y reserva una visita o una clase de prueba.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Habla con el tono de tu gimnasio y siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada de un futuro socio se queda sin atender."},
   {"icon": "funnel", "base": "clasificador-de-leads", "link": "Ver clasificador de leads",
    "title": "Seguimiento de interesados y pruebas",
    "desc": "Cada persona que pide información o viene a probar queda registrada y recibe el seguimiento adecuado, sin que tengas que acordarte.",
    "bullets": ["Recoge los contactos de la web, WhatsApp, redes y teléfono en un solo sitio.",
                "Los ordena según su interés: entrenamiento personal, clases, horario, objetivo.",
                "Mensaje de seguimiento después de la prueba, con la oferta de alta.",
                "Te avisa de los interesados más calientes para que los llames tú."],
    "result": "más visitas y pruebas que acaban en alta."},
   {"icon": "bell", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Avisos automáticos a tus socios",
    "desc": "Automatizamos los avisos que hoy haces a mano para cuidar a tus socios y no perder ni una renovación.",
    "bullets": ["Aviso antes de que venza una cuota, un bono o una matrícula.",
                "Mensaje cuando un socio lleva semanas sin venir, para animarle a volver.",
                "Recordatorio de clases reservadas y avisos de cambios de horario.",
                "Control de pagos pendientes sin revisar listados a mano."],
    "result": "menos bajas silenciosas y menos tiempo con hojas de cálculo."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("resenas-automaticas-google", "Reseñas automáticas en Google"), ("auditoria-de-procesos", "Auditoría de procesos gratuita"), ("aplicaciones-personalizadas", "Aplicaciones personalizadas")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "La gente entrena más que nunca, y espera respuesta ya",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "23", 0, "%", "de las empresas nunca respondió a una solicitud de información recibida por su web. Cada una es un socio para otro gimnasio.", "HBR · EE. UU."),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("El mercado", "1 de cada 3", 0, "", "personas encuestadas por el Consejo Superior de Deportes está abonada o es socia de un gimnasio.", "CSD · 2025"),
   ("La demanda", "53.9", 1, "%", "de la población practica deporte al menos una vez por semana. El hábito está consolidado.", "CSD · 2025"),
  ],
  "sources": sources(HBR, ZENDESK, CSD)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera pregunta a socio fiel, sin salir de la sala",
  "sub": "El recorrido de un cliente en tu gimnasio, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de entrenar a tus socios. Lo demás funciona solo.",
  "items": [
   ("chat", "<b>Pregunta.</b> Escribe por WhatsApp o llama por teléfono para saber horarios y tarifas, y recibe respuesta al momento."),
   ("calok", "<b>Prueba.</b> El asistente le reserva una visita o una clase de prueba y te deja sus datos registrados."),
   ("funnel", "<b>Seguimiento.</b> Después de la prueba recibe un mensaje con la oferta de alta, y a ti te llega el aviso si está muy interesado."),
   ("dumbbell", "<b>Entrena.</b> Ya es socio: reserva sus clases y recibe recordatorios y avisos de cambios de horario."),
   ("bell", "<b>Se queda.</b> Si deja de venir o se acerca su renovación, recibe un aviso a tiempo para que no se pierda."),
  ]},
 "steps": STEPS("gimnasio", "las consultas, las llamadas, los interesados y los avisos a socios",
                "Cargamos tus horarios, tarifas, actividades y normas del centro, y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono y tu programa de gestión."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para gimnasios en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("el programa de gestión", "tu programa de gestión de socios"),
   ("¿Puede reservar plazas en las clases dirigidas?",
    "<p>Sí, si tu programa de gestión lo permite, el asistente consulta las plazas libres y reserva directamente. Si no, recoge la petición y te la deja apuntada para que la confirmes.</p>"
    "<p>También puede avisar a los socios de cambios de horario o de clases canceladas.</p>"),
   faq_phone("cuando tu equipo está en sala", "horarios, tarifas y actividades, reserva una visita"),
   ("¿Cómo sabe qué socios han dejado de venir?",
    "<p>A partir de los accesos o las reservas que ya registra tu programa de gestión. Tú decides cuántas semanas sin venir activan el aviso y qué mensaje se envía.</p>"
    "<p>Si tu sistema no guarda esos datos, lo vemos en la auditoría y buscamos la opción más sencilla.</p>"),
   faq_datos("socios"),
   ("¿Sirve para centros deportivos, boxes o estudios de pilates?",
    "<p>Sí. Funciona igual en centros deportivos, boxes de entrenamiento funcional, estudios de pilates o yoga y centros de entrenamiento personal.</p>"
    "<p>Lo adaptamos a tus actividades y a tu forma de trabajar, tanto si trabajas con cuotas como con bonos o sesiones sueltas.</p>"),
   faq_precio("un gimnasio"),
   faq_zona("gimnasios"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a tus socios, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu gimnasio: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para gimnasios",
 "schema_desc": "IA para gimnasios en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, seguimiento de interesados y avisos automáticos a socios.",
 "yoast": yoast("IA para gimnasios en Valladolid", "asistentes de WhatsApp y teléfono, seguimiento de interesados y avisos a socios. Auditoría gratuita."),
}
