# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "peluquerias", "name": "Peluquerías", "icon": "scissors",
 "color": {"s": "#7c3aed", "dark": "#5b21b6", "light": "#d9c7fb", "soft": "#f6f1ff", "rgb": "124,58,237"},
 "credits": "cottonbro y Artbovich en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-peluqueria-estilista-color", "alt": "Estilista aplicando color a una clienta en una peluquería moderna"},
 "img2": {"file": "verantia-peluqueria-salon-moderno", "alt": "Salón de peluquería moderno y vacío, con tocadores e iluminación cálida"},
 "hero": {
  "h1": "Inteligencia artificial para <em>peluquerías</em>",
  "lead": "Tu agenda llena y tus clientes atendidos, sin soltar las tijeras. Somos especialistas en "
          "<strong>IA para peluquerías en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, recordatorios automáticos y reseñas en Google, con presupuestos ajustados a tu negocio.",
  "chips": ["Atención por WhatsApp y teléfono", "Menos huecos en la agenda", "Más reseñas en Google"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en una peluquería",
  "sub": "Manos en el pelo, secadores encendidos y un teléfono que no para. Seguro que te suena.",
  "items": [
   ("chat", "WhatsApp mientras cortas", "Te piden cita o preguntan precios por WhatsApp en plena faena. Contestas cuando puedes, y a veces ya han reservado en otro sitio."),
   ("phone", "El teléfono con las manos ocupadas", "Con un tinte a medias o el secador en la mano no puedes coger el teléfono, y esa llamada se va."),
   ("calx", "Huecos que se quedan vacíos", "Un cliente que no viene y no avisa deja un hueco en la agenda que ya nadie ocupa."),
   ("star", "Reseñas que nunca llegan", "Tus clientes salen contentos, pero casi ninguno deja su opinión en Google si nadie se lo recuerda."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual cada semana, y eso es exactamente lo que se puede automatizar sin perder el trato cercano de tu peluquería."},
 "services": {
  "eyebrow": "Soluciones para tu peluquería", "h2": "Los 4 servicios más populares en peluquerías",
  "sub": "Dos asistentes que atienden por ti y dos automatizaciones que llenan tu agenda y tu ficha de Google. Puedes empezar por uno solo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente que conoce tus servicios, tus precios y tu equipo, y que responde a tus clientes al momento, a cualquier hora, y les da cita.",
    "bullets": ["Informa de servicios, precios y duración: corte, color, mechas, tratamientos.",
                "Ofrece los huecos libres de cada estilista y reserva en tu agenda.",
                "Pregunta lo necesario antes de un servicio de color para reservar el tiempo justo.",
                "Habla con el tono de tu peluquería, cercano y profesional."],
    "result": "ningún cliente se queda sin respuesta, aunque estés con las manos ocupadas o con el salón cerrado."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas y da cita en tu agenda. Lo desarrollamos a medida para tu peluquería.",
    "bullets": ["Contesta cuando estás con un cliente, en horas punta o con el salón cerrado.",
                "Informa de servicios, precios y horarios, y reserva en tu agenda.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Habla con el tono de tu peluquería y siempre avisa de que es un asistente automático."],
    "result": "ninguna llamada se queda sin atender mientras trabajas."},
   {"icon": "bell", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Recordatorios automáticos y agenda sin huecos",
    "desc": "Automatizamos los avisos que hoy haces a mano para que las citas se confirmen solas y los huecos que se liberan vuelvan a ocuparse.",
    "bullets": ["Recordatorio por WhatsApp antes de cada cita, con opción de confirmar o cambiarla.",
                "Si alguien cancela, se avisa a los clientes en lista de espera.",
                "Aviso cuando toca volver: retoque de raíz, corte o tratamiento.",
                "Control de bonos y servicios pendientes de cada cliente."],
    "result": "menos ausencias, menos huecos muertos y clientes que vuelven a su tiempo."},
   {"icon": "star", "base": "resenas-automaticas-google", "link": "Ver reseñas automáticas en Google",
    "title": "Más reseñas en Google después de cada servicio",
    "desc": "Al terminar, tu cliente recibe un mensaje amable de agradecimiento con el enlace directo para valorar tu peluquería en Google.",
    "bullets": ["Se envía cuando la experiencia está más reciente.",
                "Llega a todos los clientes por igual, como exigen las normas de Google.",
                "Sin descuentos a cambio de reseñas: está prohibido y pone en riesgo tu ficha.",
                "Te avisa de cada reseña nueva para que puedas responderla."],
    "result": "una ficha de Google más completa y activa, que es lo primero que mira un cliente nuevo."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("ia-generativa-contenido-visual", "Contenido para redes con IA"), ("auditoria-de-procesos", "Auditoría de procesos gratuita"), ("aplicaciones-personalizadas", "Aplicaciones personalizadas")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "El teléfono sigue mandando y tus clientes esperan respuesta ya",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "57", 0, "%", "de los españoles pide cita en peluquerías y centros de belleza por teléfono. Con las manos ocupadas, esa llamada se pierde.", "Square · 2023"),
   ("Lo que esperan", "74", 0, "%", "de los consumidores espera poder recibir atención las 24 horas del día, los 7 días de la semana.", "Zendesk · 2026"),
   ("Ya lo hacen", "22.7", 1, "%", "menos citas perdidas lograron los salones de belleza que activaron la protección frente a ausencias de Booksy.", "Booksy · 2026"),
   ("La oportunidad", "13.4", 1, "%", "de las microempresas usa inteligencia artificial. La mayoría de negocios pequeños aún no ha empezado.", "INE · 2024"),
  ],
  "sources": sources(SQUARE, ZENDESK, BOOKSY, INE_IA)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera pregunta a la reseña, sin dejar las tijeras",
  "sub": "El recorrido de un cliente en tu peluquería, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas del cliente en el sillón. Lo demás funciona solo.",
  "items": [
   ("chat", "<b>Pregunta.</b> Escribe por WhatsApp o llama por teléfono para saber precios o disponibilidad, y recibe respuesta al momento."),
   ("calok", "<b>Reserva.</b> El asistente le ofrece los huecos libres de su estilista y deja la cita apuntada en tu agenda."),
   ("bell", "<b>Recordatorio.</b> Antes de la cita recibe un aviso para confirmarla o cambiarla. Si cancela, el hueco se ofrece a la lista de espera."),
   ("scissors", "<b>Servicio.</b> Tú te dedicas por completo al cliente, sin interrupciones del móvil ni del teléfono."),
   ("star", "<b>Reseña.</b> Al terminar recibe un mensaje de agradecimiento con el enlace para valorar tu peluquería en Google."),
  ]},
 "steps": STEPS("peluquería", "las citas, los mensajes, las llamadas y las reseñas",
                "Cargamos tus servicios, precios, horarios y estilistas, y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono y tu agenda."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para peluquerías en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("el programa de citas", "tu agenda"),
   ("¿Sabe el asistente cuánto dura cada servicio?",
    "<p>Sí, se lo configuramos con tus tiempos reales: no es lo mismo un corte que un color con mechas. Así reserva el hueco que de verdad necesita cada servicio y no te descuadra la agenda.</p>"
    "<p>Si un cliente pide algo fuera de lo habitual, el asistente te pasa la conversación para que lo decidas tú.</p>"),
   faq_phone("cuando estás con un cliente", "servicios, precios y horarios, reserva la cita en tu agenda"),
   faq_datos("clientes"),
   ("¿Pedir reseñas de forma automática está permitido por Google?",
    "<p>Sí. Pedir reseñas está permitido. Lo que Google prohíbe es ofrecer algo a cambio y pedírselas solo a los clientes contentos dejando fuera al resto.</p>"
    "<p>Por eso nuestro sistema pide la reseña a todos por igual y sin incentivos: tu ficha crece sin ponerla en riesgo.</p>"),
   ("¿Sirve también para barberías?",
    "<p>Sí. Funciona igual en barberías: citas por WhatsApp y teléfono, recordatorios, avisos cuando toca volver y reseñas en Google.</p>"
    "<p>Lo adaptamos a tus servicios y a tu forma de trabajar, tanto si das cita como si trabajas por orden de llegada.</p>"),
   faq_precio("una peluquería"),
   faq_zona("peluquerías"),
  ]},
 "cta": {"h2": "Dedica tu tiempo al sillón, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu peluquería: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para peluquerías",
 "schema_desc": "IA para peluquerías en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, recordatorios automáticos y reseñas en Google.",
 "yoast": yoast("IA para peluquerías en Valladolid", "asistentes virtuales de WhatsApp y teléfono, recordatorios de citas y reseñas en Google. Auditoría gratuita."),
}
