# -*- coding: utf-8 -*-
from fuentes import *
S = {
 "slug": "restaurantes", "name": "Restaurantes", "icon": "utensils",
 "color": {"s": "#dc2626", "dark": "#b91c1c", "light": "#fecaca", "soft": "#fef2f2", "rgb": "220,38,38"},
 "credits": "olly y Bertellifotografia en Pexels (licencia Pexels, uso comercial libre)",
 "img1": {"file": "verantia-restaurante-camarero-sala", "alt": "Camarero atendiendo a clientes en la sala de un restaurante"},
 "img2": {"file": "verantia-restaurante-mesas-montadas", "alt": "Mesas de restaurante montadas y listas para el servicio, sin comensales"},
 "hero": {
  "h1": "Inteligencia artificial para <em>restaurantes</em>",
  "lead": "Mesas llenas y reservas atendidas, sin que el teléfono interrumpa el servicio. Somos especialistas en "
          "<strong>IA para restaurantes en Valladolid</strong> y en toda España: asistentes virtuales para WhatsApp, "
          "la web y el teléfono, confirmación automática de reservas y reseñas en Google, con presupuestos ajustados a tu negocio.",
  "chips": ["Reservas por WhatsApp y teléfono", "Menos mesas vacías", "Más reseñas en Google"]},
 "pains": {
  "eyebrow": "El día a día", "h2": "Lo que se come el tiempo en un restaurante",
  "sub": "Sala llena, comandas saliendo de cocina y un teléfono que suena en el peor momento. Seguro que te suena.",
  "items": [
   ("chat", "Reservas por WhatsApp en pleno servicio", "Te piden mesa, preguntan por la carta o por opciones sin gluten mientras sirves. Contestas cuando puedes, y a veces ya han reservado en otro sitio."),
   ("phone", "El teléfono en plena hora punta", "Con la sala llena nadie puede coger el teléfono, y esa llamada suele ser una mesa para esta noche o un grupo para el fin de semana."),
   ("calx", "Mesas reservadas que se quedan vacías", "Una reserva que no se presenta y no avisa deja una mesa sin ocupar que ya no puedes ofrecer a nadie."),
   ("star", "Reseñas que nunca llegan", "Tus clientes salen contentos, pero casi ninguno deja su opinión en Google si nadie se lo recuerda."),
  ],
  "summary": "<strong>La buena noticia:</strong> casi todas estas tareas se repiten igual en cada servicio, y eso es exactamente lo que se puede automatizar sin perder el trato cercano de tu restaurante."},
 "services": {
  "eyebrow": "Soluciones para tu restaurante", "h2": "Los 4 servicios más populares en restaurantes",
  "sub": "Dos asistentes que atienden reservas por ti y dos automatizaciones que llenan tus mesas y tu ficha de Google. Puedes empezar por uno solo.",
  "items": [
   {"icon": "chat", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente virtual para WhatsApp y tu web",
    "desc": "Un asistente que conoce tu carta, tus horarios y tus turnos, y que responde a tus clientes al momento, a cualquier hora, y les reserva mesa.",
    "bullets": ["Informa de carta, menú del día, alérgenos y horarios.",
                "Ofrece los turnos disponibles y apunta la reserva.",
                "Recoge lo importante: número de comensales, trona, terraza o celebración.",
                "Te pasa los grupos grandes y los eventos para que los cierres tú."],
    "result": "ninguna reserva se queda sin respuesta, aunque estés en pleno servicio o con el local cerrado."},
   {"icon": "phoneai", "base": "chatbots-asistentes-virtuales", "link": "Ver asistentes virtuales",
    "title": "Asistente telefónico con inteligencia artificial",
    "desc": "Una voz natural que atiende las llamadas que tú no puedes coger: resuelve dudas y toma reservas. Lo desarrollamos a medida para tu restaurante.",
    "bullets": ["Contesta en plena hora punta, en tu día de descanso o con el local cerrado.",
                "Informa de horarios, carta y ubicación, y toma la reserva.",
                "Si la consulta necesita a una persona, toma el recado para que devuelvas la llamada.",
                "Habla con el tono de tu restaurante y siempre avisa de que es un asistente automático."],
    "result": "el teléfono deja de interrumpir el servicio y ninguna llamada se queda sin atender."},
   {"icon": "bell", "base": "automatizacion-de-procesos", "link": "Ver automatización de procesos",
    "title": "Confirmación automática de reservas",
    "desc": "Automatizamos los avisos que hoy haces a mano para que las reservas se confirmen solas y las mesas que se liberan vuelvan a ofrecerse.",
    "bullets": ["Mensaje por WhatsApp antes de la reserva para confirmarla o cancelarla.",
                "Si alguien cancela, la mesa vuelve a quedar disponible al momento.",
                "Recordatorio con la dirección y la hora, para que nadie se pierda.",
                "Para grupos y fechas señaladas, confirmación con más antelación."],
    "result": "menos mesas vacías por reservas que no se presentan."},
   {"icon": "star", "base": "resenas-automaticas-google", "link": "Ver reseñas automáticas en Google",
    "title": "Más reseñas en Google después de cada visita",
    "desc": "Después de la comida o la cena, tu cliente recibe un mensaje amable de agradecimiento con el enlace directo para valorar tu restaurante en Google.",
    "bullets": ["Se envía cuando la experiencia está más reciente.",
                "Llega a todos los clientes por igual, como exigen las normas de Google.",
                "Sin descuentos ni invitaciones a cambio de reseñas: está prohibido y pone en riesgo tu ficha.",
                "Te avisa de cada reseña nueva para que puedas responderla."],
    "result": "una ficha de Google más completa y activa, que es lo que mira quien busca dónde comer."},
  ],
  "also_intro": "También te puede interesar:",
  "also": [("ia-generativa-contenido-visual", "Fotos y textos para redes con IA"), ("auditoria-de-procesos", "Auditoría de procesos gratuita"), ("aplicaciones-personalizadas", "Aplicaciones personalizadas")]},
 "stats": {
  "eyebrow": "Por qué ahora", "h2": "El teléfono sigue trayendo mesas, y las reseñas deciden",
  "sub": "Cuatro datos públicos que resumen el problema y la oportunidad. Ninguno es una estimación nuestra.",
  "items": [
   ("El problema", "34", 0, "%", "de las reservas en restaurantes sigue llegando por teléfono, muchas veces en plena hora punta.", "CoverManager · 2025"),
   ("Ya lo hacen", "7", 0, "%", "de las reservas telefónicas ya las atiende un asistente de voz con inteligencia artificial.", "CoverManager · 2025"),
   ("Lo que miran", "89", 0, "%", "de los españoles consulta reseñas online antes de comprar. Antes de elegir restaurante, también.", "Skeepers · 2025"),
   ("La oportunidad", "2", 0, "%", "de reservas no presentadas en los restaurantes que confirman la reserva y piden señal.", "CoverManager · 2025"),
  ],
  "sources": sources(COVER, SKEEPERS)},
 "day": {
  "eyebrow": "Así funciona", "h2": "De la primera pregunta a la reseña, sin dejar la sala",
  "sub": "El recorrido de un cliente en tu restaurante, con las cuatro soluciones trabajando juntas.",
  "caption": "Tú te ocupas de la sala y la cocina. Lo demás funciona solo.",
  "items": [
   ("chat", "<b>Pregunta.</b> Escribe por WhatsApp o llama por teléfono para saber si hay mesa, ver la carta o preguntar por alérgenos, y recibe respuesta al momento."),
   ("calok", "<b>Reserva.</b> El asistente le ofrece los turnos libres y deja la reserva apuntada con todos los detalles."),
   ("bell", "<b>Confirmación.</b> Antes de la reserva recibe un mensaje para confirmarla o cancelarla. Si cancela, la mesa vuelve a quedar libre."),
   ("utensils", "<b>Servicio.</b> Tu equipo se dedica por completo a la sala, sin interrupciones del teléfono."),
   ("star", "<b>Reseña.</b> Después de la visita recibe un mensaje de agradecimiento con el enlace para valorar tu restaurante en Google."),
  ]},
 "steps": STEPS("restaurante", "las reservas, los mensajes, las llamadas y las reseñas",
                "Cargamos tu carta, alérgenos, horarios, turnos y aforo, y tu forma de hablar. Conectamos tu WhatsApp, tu teléfono y tu sistema de reservas."),
 "faq": {
  "eyebrow": "Preguntas frecuentes", "h2": "Preguntas frecuentes sobre IA para restaurantes en Valladolid",
  "sub": "Respuestas claras, sin tecnicismos. Si te falta alguna, escríbenos.",
  "items": [
   faq_software("el sistema de reservas", "tu sistema de reservas"),
   ("¿Puede informar de alérgenos?",
    "<p>Sí, a partir de la información de tu carta que tú nos das y revisas. El asistente responde con esos datos y nunca se los inventa.</p>"
    "<p>Cuando un cliente tiene una alergia grave o una duda que no está en la carta, el asistente te pasa la consulta para que responda tu equipo.</p>"),
   faq_phone("en plena hora punta", "horarios, carta y ubicación, toma la reserva"),
   ("¿Qué pasa con los grupos grandes y los eventos?",
    "<p>Tú decides a partir de cuántos comensales quieres gestionarlos en persona. El asistente recoge los datos del grupo o del evento y te los pasa para que lo cierres tú.</p>"
    "<p>Así no pierdes el contacto con las reservas más importantes, y te ahorras el ir y venir de mensajes del resto.</p>"),
   faq_datos("clientes"),
   ("¿Pedir reseñas de forma automática está permitido por Google?",
    "<p>Sí. Pedir reseñas está permitido. Lo que Google prohíbe es ofrecer algo a cambio, como un postre o un descuento, y pedírselas solo a los clientes contentos dejando fuera al resto.</p>"
    "<p>Por eso nuestro sistema pide la reseña a todos por igual y sin incentivos: tu ficha crece sin ponerla en riesgo.</p>"),
   faq_precio("un restaurante"),
   faq_zona("restaurantes"),
  ]},
 "cta": {"h2": "Dedica tu tiempo a la sala, no al teléfono",
         "p": "Empezamos con una auditoría gratuita de tu restaurante: vemos cómo trabajas hoy y te decimos qué merece la pena automatizar. Si no te compensa, te lo diremos igual."},
 "schema_type": "Inteligencia artificial para restaurantes",
 "schema_desc": "IA para restaurantes en Valladolid y toda España: asistentes virtuales para WhatsApp, la web y el teléfono, confirmación automática de reservas y reseñas en Google.",
 "yoast": yoast("IA para restaurantes en Valladolid", "reservas por WhatsApp y teléfono, confirmaciones automáticas y más reseñas en Google. Auditoría gratuita."),
}
